version: '3.8'

services:
  mysql_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ayuda123
      - MYSQL_DATABASE=ayudameapp
    ports:
      - 3306:3306

  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    links:
      - mysql_db
    ports:
      - 3001:3001
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
  # api:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - 3003:3003
  #   depends_on:
  #     - mysql
  #   links:
  #     - mysql
